[credentials.usernames.jsmith]
email = "bonvn133@gmail.com"
name = "Tran Phuc Khanh"
password = "$2b$12$/vXUyuhwdlNZT2O4QeFRgOx7P7g3C/3CwMdfqsQxGRdLC6Ji7VvzC"

[credentials.usernames.rbriggs]
email = "macphuckhang11112007@gmail.com"
name = "Mac Phuc Khang"
password = "$2b$12$/vXUyuhwdlNZT2O4QeFRgOx7P7g3C/3CwMdfqsQxGRdLC6Ji7VvzC"

[cookie]
expiry_days = 30
key = "aaaaaaaaaaaaaaaasaaa"
name = "login-cookie (riu)"

[preauthorized]
emails = [ "trangiahuy211207@gmail.com" ]

[project-info]
pass = w8qHpfGPzZMSviaG
url = "https://zwiuiboxrduhnkawwnxg.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3aXVpYm94cmR1aG5rYXd3bnhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODUwMjUyODMsImV4cCI6MjAwMDYwMTI4M30.g8iSc7_F0PirUd3GcxYYlEZ-60sONXRiYg_L58mD3Ro"

[database-user-login]
email = trangiahuy211207@gmail.com
pass = huy21121234